---
  - name: Install Apache
    when: ansible_facts['distribution_major_version'] == '7'
    yum:
      name: 
        - httpd
      state: latest
  
  - name: Start th Apache
    when: ansible_facts['distribution_major_version'] == '7'
    systemd:
      name: httpd
      state: started