---
  - name: Install Apache
    when: ansible_hostname == 'app'
    yum:
      name:
        - httpd
      state: latest
  
  - name: Start the Apache
    when: ansible_hostname == 'app'
    systemd:
      name: httpd
      state: started