---
  - name: User Management 
    hosts: "{{ group }}"
    gather_facts: "{{gather_facts}}"
    vars_files:
      - "../variables/addusers-values.yaml"
    tasks:
    ### Task for User 1 value defines in "../variables/addusers-values.yaml"
      - name: Add User 1 
        user:
          name: "{{user_name1}}"
          uid: "{{user_uid1}}"

    ### Task for User 2 value defines in "../variables/addusers-values.yaml"
      - name: Add User 2 
        user:
          name: "{{user_name2}}"
          uid: "{{user_uid2}}"