---
  - name: This playbook will delete folder in remote hosts
    hosts: production
    tasks:
      - name: Delete "testfolder5" under /tmp
        file:
          path: /tmp/testfolder5
          state: absent
