---
  - name: This playbook will run "ls" command
    hosts: development
    gather_facts: no
    tasks:
      - name: Ping Hosts
        ping:

      - name: run "ls" command
        command: "{{item}}"
        with_items:
          - pwd
          - ls            
        register: command_output

      - name: Run 'debug' to read command_output
        debug:
          var: command_output