---
  - name: This playbook will checks free disk in remote hosts.
    hosts: "{{group}}"
    tasks:
      - name: running "df -h" command on CentOS 7
        when: ansible_distribution_major_version == "7" and ansible_distribution == "CenOS7"
        command: df -h
        register: command_output
      - name: Run 'debug' to read command_output
        debug: var=command_output