---
  - name: Thos playbook will install LAMP
    hosts: dev-servers
    tasks:
      - name: Install packages httpd, php, php-mysql on CentOS6
        when: ansible_distribution_major_version == "6"
        yum:
          name:
            - httpd
            - php
            - php-mysql
          state: latest

      - name: Install the latest version of MariaDB on  CentOS7
        when: ansible_distribution_major_version == "7"
        yum:
          name:
            - mariadb-server
            - mariadb
          state: latest

      - name: Start HTTPD on CentOS6
        when: ansible_distribution_major_version == "6"
        service:
          state: started
          enabled: yes
          name: httpd

      - name: Start and Restart service MariqDB on CenOS7, if not started 
        when: ansible_distribution_major_version == "7"
        systemd:
          name: mariadb
          state: started
          enabled: yes