---
  - name: Thos playbook will install LAMP
    hosts: dev-servers
    tasks:
      - name: Install packages httpd, php, php-mysql on CentOS6
        when: ansible_distribution_major_version == "6"
        yum:
          name:
            - httpd
            - php
            - php-mysql
          state: latest

      - name: Start HTTPD on CentOS6
        when: ansible_distribution_major_version == "6"
        service:
          name: httpd
          state: started
          enabled: yes

      - name: downloaded Wordpress on CentOS6
        when: ansible_distribution_major_version == "6" 
        get_url:
          url: https://wordpress.org/latest.tar.gz
          dest: /tmp/

      - name: Unarchive a file that is already on the remote machine
        when: ansible_distribution_major_version == "6"
        unarchive:
          src: /tmp/wordpress-5.5.1.tar.gz
          dest: /tmp
          remote_src: yes

      - name: copy wordpress/* to /var/www/html
        when: ansible_distribution_major_version == "6"
        shell:
          cmd: cp -r /tmp/wordpress/* /var/www/html

      - name: create a file info.php
        when: ansible_distribution_major_version == "6"
        file:
          path: /var/www/html/info.php
          state: touch 

      - name: write in info.php
        when: ansible_distribution_major_version == "6"
        blockinfile:
          path: /var/www/html/info.php
          block: |
            <?php
            phpinfo();
            ?>