---
  - name: Thos playbook will install LAMP
    hosts: host1
    tasks:
      - name: Install packages httpd, php, php-mysql on CentOS6
        when: ansible_distribution_major_version == "6"
        yum:
          name:
            - httpd
            - php
            - php-mysql
          state: latest

      - name: Start HTTPD on CentOS6
        when: ansible_distribution_major_version == "6"
        service:
          name: httpd
          state: started
          enabled: yes

      - name: Download the latest version of WordPress
        get_url: 
          url: https://wordpress.org/latest.tar.gz
          dest: ~/worldpress

      - name: Unarchive a file that we judt downloaded
        unarchive:
          src: https://wordpress.org/latest.tar.gz
          dest: ~/wordpress

      - name: create a directory html
        file:
          path: /var/www/html
          state: directory

      - name: create a file info.php
        file:
          path: /var/www/html/info.php
          state: touch 
          
      - name: write in info.php
        blockinfile:
          path: /var/www/html/info.php
          block: |
            <?php
            phpinfo();
            ?>

      - name: copy wordpress/* to /var/www/html
        copy:
          src: ~/wordpress/*
          dest: /var/www/html

      - name: create wp-cinfig.php
        file:
          path: ~/wordpress/wp-config.php
          state: touch

      - name: copy wordpress/wp-config-sample.php to wordpress/wp-config.php
        copy:
          src: ~/wordpress/wp-config-sample.php
          dest: ~/wordpress/wp-config.php

      #- name: Install the latest version of MariaDB on  CentOS7
      #  when: ansible_distribution_major_version == "7"
      #  yum:
      #    name:
      #      - mariadb-server
      #      - mariadb
      #    state: latest
#
      #- name: Start and Restart service MariaDB on CenOS7, 
      #  when: ansible_distribution_major_version == "7"
      #  systemd:
      #    name: mariadb
      #    state: started
      #    enabled: yes
